MUL-2716 Wyszukiwarka CMS - Sortowanie wyników
milejko/mmi-cms pull request #263
Opened 2024-02-21 10:50 UTC by telemetricsystems

2024-02-21 11:12 UTC, milejko requested changes

2024-02-21 11:12 UTC, milejko commented on src/Cms/Orm/CmsCategoryQuery.php
> +        $this->_compile->order .= ($this->_compile->order ? ',' : 'ORDER BY') . " IF($customUri IS NOT NULL AND LENGTH($customUri) > 0, $customUri, $uri) " . ($asc ? 'ASC' : 'DESC');
nope

2024-02-21 12:14 UTC, cezolk approved these changes

2024-02-22 11:39 UTC, milejko approved these changes

2024-02-22 11:50 UTC, merged